// <auto-generated/>

namespace Sample
{
partial interface ISample2
{
    void Accept(Sample.ISample2Visitor visitor);
}
}

namespace Sample
{
partial interface ISample2Visitor
{
    void Visit(Sample.Sample1 value);
    void Visit(Sample.Sample2 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample2
{
    void Sample.ISample2.Accept(Sample.ISample2Visitor visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample2
{
    void Sample.ISample2.Accept(Sample.ISample2Visitor visitor) => visitor.Visit(this);
}
}
