// <auto-generated/>

namespace Sample.SampleRequest
{
partial interface ISampleRequest
{
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> AcceptAsync<TArg1, TArg2>(Sample.SampleRequest.ISampleRequestVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2);
}
}

namespace Sample.SampleRequest
{
partial interface ISampleRequestVisitor2<in TArg1, in TArg2>
{
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> VisitAsync(Sample.SampleRequest.Sample3Request value, TArg1 arg1, TArg2 arg2);
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.Sample1Response> VisitAsync(Sample.SampleRequest.Sample1Request value, TArg1 arg1, TArg2 arg2);
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.Sample2Response> VisitAsync(Sample.SampleRequest.Sample2Request value, TArg1 arg1, TArg2 arg2);
}
}

namespace Sample.SampleRequest
{
partial class Sample3Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.ISampleResponse>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1, TArg2>(Sample.SampleRequest.ISampleRequestVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => await visitor.VisitAsync(this, arg1, arg2);
}
}

namespace Sample.SampleRequest
{
partial class Sample1Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.Sample1Response>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1, TArg2>(Sample.SampleRequest.ISampleRequestVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => (Sample.SampleResponse.ISampleResponse)await visitor.VisitAsync(this, arg1, arg2);
}
}

namespace Sample.SampleRequest
{
partial class Sample2Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.Sample2Response>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1, TArg2>(Sample.SampleRequest.ISampleRequestVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => (Sample.SampleResponse.ISampleResponse)await visitor.VisitAsync(this, arg1, arg2);
}
}
