// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    TResult Accept<TArg1, TArg2, TArg3, TResult>(Sample.ISampleVisitor3<TArg1, TArg2, TArg3, TResult> visitor, TArg1 arg1, TArg2 arg2, TArg3 arg3);
}
}

namespace Sample
{
partial interface ISampleVisitor3<in TArg1, in TArg2, in TArg3, out TResult>
{
    TResult Visit(Sample.Sample1 value, TArg1 arg1, TArg2 arg2, TArg3 arg3);
    TResult Visit(Sample.Sample2 value, TArg1 arg1, TArg2 arg2, TArg3 arg3);
    TResult Visit(Sample.Sample3 value, TArg1 arg1, TArg2 arg2, TArg3 arg3);
    TResult Visit(Sample.Sample4 value, TArg1 arg1, TArg2 arg2, TArg3 arg3);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    TResult Sample.ISample.Accept<TArg1, TArg2, TArg3, TResult>(Sample.ISampleVisitor3<TArg1, TArg2, TArg3, TResult> visitor, TArg1 arg1, TArg2 arg2, TArg3 arg3) => visitor.Visit(this, arg1, arg2, arg3);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    TResult Sample.ISample.Accept<TArg1, TArg2, TArg3, TResult>(Sample.ISampleVisitor3<TArg1, TArg2, TArg3, TResult> visitor, TArg1 arg1, TArg2 arg2, TArg3 arg3) => visitor.Visit(this, arg1, arg2, arg3);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    TResult Sample.ISample.Accept<TArg1, TArg2, TArg3, TResult>(Sample.ISampleVisitor3<TArg1, TArg2, TArg3, TResult> visitor, TArg1 arg1, TArg2 arg2, TArg3 arg3) => visitor.Visit(this, arg1, arg2, arg3);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    TResult Sample.ISample.Accept<TArg1, TArg2, TArg3, TResult>(Sample.ISampleVisitor3<TArg1, TArg2, TArg3, TResult> visitor, TArg1 arg1, TArg2 arg2, TArg3 arg3) => visitor.Visit(this, arg1, arg2, arg3);
}
}
