// <auto-generated/>

namespace Sample.SampleResponse
{
[MessagePack.Union(1, typeof(Sample.SampleResponse.Sample1Response))]
[MessagePack.Union(2, typeof(Sample.SampleResponse.Sample2Response))]
partial interface ISampleResponse { }
}
