// <auto-generated/>

namespace Sample.SampleRequest
{
[MessagePack.Union(1, typeof(Sample.SampleRequest.Sample1Request))]
[MessagePack.Union(2, typeof(Sample.SampleRequest.Sample2Request))]
[MessagePack.Union(3, typeof(Sample.SampleRequest.Sample3Request))]
partial interface ISampleRequest { }
}
