// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    TResult Accept<TResult>(Sample.ISampleVisitor<TResult> visitor);
}
}

namespace Sample
{
partial interface ISampleVisitor<out TResult>
{
    TResult Visit(Sample.Sample1 value);
    TResult Visit(Sample.Sample2 value);
    TResult Visit(Sample.Sample3 value);
    TResult Visit(Sample.Sample4 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    TResult Sample.ISample.Accept<TResult>(Sample.ISampleVisitor<TResult> visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    TResult Sample.ISample.Accept<TResult>(Sample.ISampleVisitor<TResult> visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    TResult Sample.ISample.Accept<TResult>(Sample.ISampleVisitor<TResult> visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    TResult Sample.ISample.Accept<TResult>(Sample.ISampleVisitor<TResult> visitor) => visitor.Visit(this);
}
}
