// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    System.Threading.Tasks.ValueTask<TResult> AcceptAsync<TResult>(Sample.ISampleValueTaskVisitor<TResult> visitor);
}
}

namespace Sample
{
partial interface ISampleValueTaskVisitor<TResult>
{
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample1 value);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample2 value);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample3 value);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample4 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TResult>(Sample.ISampleValueTaskVisitor<TResult> visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TResult>(Sample.ISampleValueTaskVisitor<TResult> visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TResult>(Sample.ISampleValueTaskVisitor<TResult> visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TResult>(Sample.ISampleValueTaskVisitor<TResult> visitor) => await visitor.VisitAsync(this);
}
}
