// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    void Accept(Sample.ISampleVisitor visitor);
}
}

namespace Sample
{
partial interface ISampleVisitor
{
    void Visit(Sample.Sample1 value);
    void Visit(Sample.Sample2 value);
    void Visit(Sample.Sample3 value);
    void Visit(Sample.Sample4 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    void Sample.ISample.Accept(Sample.ISampleVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    void Sample.ISample.Accept(Sample.ISampleVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    void Sample.ISample.Accept(Sample.ISampleVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    void Sample.ISample.Accept(Sample.ISampleVisitor visitor) => visitor.Visit(this);
}
}
