// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    System.Threading.Tasks.ValueTask AcceptAsync(Sample.ISampleValueTaskVisitor visitor);
}
}

namespace Sample
{
partial interface ISampleValueTaskVisitor
{
    System.Threading.Tasks.ValueTask VisitAsync(Sample.Sample1 value);
    System.Threading.Tasks.ValueTask VisitAsync(Sample.Sample2 value);
    System.Threading.Tasks.ValueTask VisitAsync(Sample.Sample3 value);
    System.Threading.Tasks.ValueTask VisitAsync(Sample.Sample4 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    async System.Threading.Tasks.ValueTask Sample.ISample.AcceptAsync(Sample.ISampleValueTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    async System.Threading.Tasks.ValueTask Sample.ISample.AcceptAsync(Sample.ISampleValueTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    async System.Threading.Tasks.ValueTask Sample.ISample.AcceptAsync(Sample.ISampleValueTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    async System.Threading.Tasks.ValueTask Sample.ISample.AcceptAsync(Sample.ISampleValueTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}
