// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    void Accept<TArg1>(Sample.ISampleVisitor1<TArg1> visitor, TArg1 arg1);
}
}

namespace Sample
{
partial interface ISampleVisitor1<in TArg1>
{
    void Visit(Sample.Sample1 value, TArg1 arg1);
    void Visit(Sample.Sample2 value, TArg1 arg1);
    void Visit(Sample.Sample3 value, TArg1 arg1);
    void Visit(Sample.Sample4 value, TArg1 arg1);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    void Sample.ISample.Accept<TArg1>(Sample.ISampleVisitor1<TArg1> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    void Sample.ISample.Accept<TArg1>(Sample.ISampleVisitor1<TArg1> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    void Sample.ISample.Accept<TArg1>(Sample.ISampleVisitor1<TArg1> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    void Sample.ISample.Accept<TArg1>(Sample.ISampleVisitor1<TArg1> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}
