// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    System.Threading.Tasks.ValueTask<TResult> AcceptAsync<TArg1, TResult>(Sample.ISampleValueTaskVisitor1<TArg1, TResult> visitor, TArg1 arg1);
}
}

namespace Sample
{
partial interface ISampleValueTaskVisitor1<in TArg1, TResult>
{
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample1 value, TArg1 arg1);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample2 value, TArg1 arg1);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample3 value, TArg1 arg1);
    System.Threading.Tasks.ValueTask<TResult> VisitAsync(Sample.Sample4 value, TArg1 arg1);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TArg1, TResult>(Sample.ISampleValueTaskVisitor1<TArg1, TResult> visitor, TArg1 arg1) => await visitor.VisitAsync(this, arg1);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TArg1, TResult>(Sample.ISampleValueTaskVisitor1<TArg1, TResult> visitor, TArg1 arg1) => await visitor.VisitAsync(this, arg1);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TArg1, TResult>(Sample.ISampleValueTaskVisitor1<TArg1, TResult> visitor, TArg1 arg1) => await visitor.VisitAsync(this, arg1);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    async System.Threading.Tasks.ValueTask<TResult> Sample.ISample.AcceptAsync<TArg1, TResult>(Sample.ISampleValueTaskVisitor1<TArg1, TResult> visitor, TArg1 arg1) => await visitor.VisitAsync(this, arg1);
}
}
