// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    void Accept<TArg1, TArg2>(Sample.ISampleVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2);
}
}

namespace Sample
{
partial interface ISampleVisitor2<in TArg1, in TArg2>
{
    void Visit(Sample.Sample1 value, TArg1 arg1, TArg2 arg2);
    void Visit(Sample.Sample2 value, TArg1 arg1, TArg2 arg2);
    void Visit(Sample.Sample3 value, TArg1 arg1, TArg2 arg2);
    void Visit(Sample.Sample4 value, TArg1 arg1, TArg2 arg2);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    void Sample.ISample.Accept<TArg1, TArg2>(Sample.ISampleVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => visitor.Visit(this, arg1, arg2);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    void Sample.ISample.Accept<TArg1, TArg2>(Sample.ISampleVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => visitor.Visit(this, arg1, arg2);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    void Sample.ISample.Accept<TArg1, TArg2>(Sample.ISampleVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => visitor.Visit(this, arg1, arg2);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    void Sample.ISample.Accept<TArg1, TArg2>(Sample.ISampleVisitor2<TArg1, TArg2> visitor, TArg1 arg1, TArg2 arg2) => visitor.Visit(this, arg1, arg2);
}
}
