// <auto-generated/>

namespace Sample.SampleResponse
{
partial interface ISampleResponse
{
    void Accept(Sample.SampleResponse.ISampleResponseVisitor visitor);
}
}

namespace Sample.SampleResponse
{
partial interface ISampleResponseVisitor
{
    void Visit(Sample.SampleResponse.Sample1Response value);
    void Visit(Sample.SampleResponse.Sample2Response value);
}
}

namespace Sample.SampleResponse
{
partial class Sample1Response: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample.SampleResponse
{
partial class Sample2Response: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}
