// <auto-generated/>

namespace Sample
{
partial interface ISample
{
    System.Threading.Tasks.Task AcceptAsync(Sample.ISampleTaskVisitor visitor);
}
}

namespace Sample
{
partial interface ISampleTaskVisitor
{
    System.Threading.Tasks.Task VisitAsync(Sample.Sample1 value);
    System.Threading.Tasks.Task VisitAsync(Sample.Sample2 value);
    System.Threading.Tasks.Task VisitAsync(Sample.Sample3 value);
    System.Threading.Tasks.Task VisitAsync(Sample.Sample4 value);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample
{
    async System.Threading.Tasks.Task Sample.ISample.AcceptAsync(Sample.ISampleTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample
{
    async System.Threading.Tasks.Task Sample.ISample.AcceptAsync(Sample.ISampleTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample3: Sample.ISample
{
    async System.Threading.Tasks.Task Sample.ISample.AcceptAsync(Sample.ISampleTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}

namespace Sample
{
partial class Sample4: Sample.ISample
{
    async System.Threading.Tasks.Task Sample.ISample.AcceptAsync(Sample.ISampleTaskVisitor visitor) => await visitor.VisitAsync(this);
}
}
