// <auto-generated/>

namespace Sample.SampleRequest
{
partial interface ISampleRequest
{
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> AcceptAsync<TArg1>(Sample.SampleRequest.ISampleRequestVisitor1<TArg1> visitor, TArg1 arg1);
}
}

namespace Sample.SampleRequest
{
partial interface ISampleRequestVisitor1<in TArg1>
{
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> VisitAsync(Sample.SampleRequest.Sample3Request value, TArg1 arg1);
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.Sample1Response> VisitAsync(Sample.SampleRequest.Sample1Request value, TArg1 arg1);
    System.Threading.Tasks.ValueTask<Sample.SampleResponse.Sample2Response> VisitAsync(Sample.SampleRequest.Sample2Request value, TArg1 arg1);
}
}

namespace Sample.SampleRequest
{
partial class Sample3Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.ISampleResponse>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1>(Sample.SampleRequest.ISampleRequestVisitor1<TArg1> visitor, TArg1 arg1) => await visitor.VisitAsync(this, arg1);
}
}

namespace Sample.SampleRequest
{
partial class Sample1Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.Sample1Response>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1>(Sample.SampleRequest.ISampleRequestVisitor1<TArg1> visitor, TArg1 arg1) => (Sample.SampleResponse.ISampleResponse)await visitor.VisitAsync(this, arg1);
}
}

namespace Sample.SampleRequest
{
partial class Sample2Request: Sample.SampleRequest.ISampleRequest, Sample.IVisitorResult<Sample.SampleResponse.Sample2Response>
{
    async System.Threading.Tasks.ValueTask<Sample.SampleResponse.ISampleResponse> Sample.SampleRequest.ISampleRequest.AcceptAsync<TArg1>(Sample.SampleRequest.ISampleRequestVisitor1<TArg1> visitor, TArg1 arg1) => (Sample.SampleResponse.ISampleResponse)await visitor.VisitAsync(this, arg1);
}
}
