// <auto-generated/>

namespace Sample
{
partial interface ISample2
{
    TResult Accept<TArg1, TResult>(Sample.ISample2Visitor1<TArg1, TResult> visitor, TArg1 arg1) where TArg1 : class, new() where TResult : struct;
}
}

namespace Sample
{
partial interface ISample2Visitor1<in TArg1, out TResult>
{
    TResult Visit(Sample.Sample1 value, TArg1 arg1);
    TResult Visit(Sample.Sample2 value, TArg1 arg1);
}
}

namespace Sample
{
partial class Sample1: Sample.ISample2
{
    TResult Sample.ISample2.Accept<TArg1, TResult>(Sample.ISample2Visitor1<TArg1, TResult> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}

namespace Sample
{
partial class Sample2: Sample.ISample2
{
    TResult Sample.ISample2.Accept<TArg1, TResult>(Sample.ISample2Visitor1<TArg1, TResult> visitor, TArg1 arg1) => visitor.Visit(this, arg1);
}
}
