// <auto-generated/>

namespace Sample.SampleResponse
{
partial interface ISampleResponse
{
    void Accept(Sample.SampleResponse.ISampleResponseVisitor visitor);
}
}

namespace Sample.SampleResponse
{
partial interface ISampleResponseVisitor
{
    void Visit(Sample.SampleResponse.SampleResponse1 value);
    void Visit(Sample.SampleResponse.SampleResponse2 value);
    void Visit(Sample.SampleResponse.SampleResponse3 value);
    void Visit(Sample.SampleResponse.SampleResponse4 value);
}
}

namespace Sample.SampleResponse
{
partial class SampleResponse1: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample.SampleResponse
{
partial class SampleResponse2: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample.SampleResponse
{
partial class SampleResponse3: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}

namespace Sample.SampleResponse
{
partial class SampleResponse4: Sample.SampleResponse.ISampleResponse
{
    void Sample.SampleResponse.ISampleResponse.Accept(Sample.SampleResponse.ISampleResponseVisitor visitor) => visitor.Visit(this);
}
}
